### ISSUE TITLE
Needs graceful handling of SIGPIPE

### ISSUE THREAD

**Issue by selik** [jcushman/xport#1]
http://en.wikipedia.org/wiki/SIGPIPE

If I try to check a small amount of output by piping to head

```
$ python ~/src/xport/xport/xport.py ~/data/file.xpt | head -n 5
```

It'll parse the file properly, print the first n lines and then give an error

```
Traceback (most recent call last):
  File "/Users/mike/src/xport/xport/xport.py", line 283, in <module>
    print obj
IOError: [Errno 32] Broken pipe
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

I tried catching the IOError, checking for the Errno that indicates SIGPIPE, and then exiting. That avoids the traceback, but the with block still tries to close the file even though the file is already closed, so the second error, "close failed ..." still gets printed to stdout.

**Comment by jcushman** [comment]
I just committed something to handle this -- if you call sys.exit() from the "except IOError", it seems to escape the with block without any further exceptions.

https://github.com/jcushman/xport/commit/37af428315c1a2fcf3dfa64acf124a3b4ea8a0ed

Let me know if this works for you (or if you're still getting other cruft printed), and I can push out a revised package.

**Comment by selik** [comment]
That's what I had tried before. It takes care of the IOError, but not the close failing in the object destructor.

```
$ python xport/xport.py ~/data/nhanes/BMX_F.xpt | head -n 1
{'BMXTRI': 16, 'BMILEG': 0, 'BMXHEAD': 0, 'BMXLEG': 41, 'BMIWT': 0, 'BMIWAIST': 0, 'BMXBMI': 32, 'BMXRECUM': 0, 'BMIARMC': 0, 'BMIARML': 0, 'BMIHT': 0, 'BMIRECUM': 0, 'BMITRI': 0, 'BMXARML': 40, 'BMISUB': 0, 'BMIHEAD': 0, 'BMXWT': 87, 'BMXARMC': 36, 'SEQN': 51624, 'BMXWAIST': 100, 'BMXSUB': 24, 'BMXHT': 164, 'BMDSTATS': 1}
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr
```

I started refactoring to cap lines at 80 characters. I ended up making more changes than I originally intended: https://github.com/selik/xport/blob/toCSV/xport/xport.py. This doesn't cause the failed object destructor, perhaps because it doesn't open the file, but I'm not sure why that would change the destructor behavior.

**Comment by jcushman** [comment]
Hmm. What version of Python are you using? I'm on 2.7.1 (OS X 10.7.4), and
don't get the "close failed in file ..." junk when I call sys.exit() from
the except block. There's an old bug (I'm not finding it immediately) from
Python 2.4 or so that reported the same problem and was closed as no longer
applicable.

Or if you're on a recent Python, is it possible there's some race condition
here? When you kill a piped command with ctrl-c or whatever, apparently you
can get the error you're describing intermittently depending which process
receives the signal first:  http://bugs.python.org/issue11380

(Neither of these seem likely -- just brainstorming as to why we're seeing
different output.)

Anyway -- I don't really have much occasion to parse xpt files, and you're
obviously doing a lot of work cleaning this up. If you're interested in
taking over the module, I'd be happy to transfer ownership to you on PyPI,
although I'm not 100% sure how to do that.

On Mon, Jul 16, 2012 at 2:09 PM, Michael Selik <
reply@reply.github.com

**Comment by selik** [comment]
I produced the error message with Python 2.7.2 on Mac OS X 10.7.4. I came across the same issue post. It seems like this is something that could get fixed with the next interpreter update. It's minor enough to ignore.

I wouldn't mind taking over the module on PyPI. Then I'd feel obligated to enable parsing multiple members/datasets in the same file.
